### ISSUE TITLE
Add custom style

### ISSUE THREAD

**Issue by nothanks1** [jmaupetit/md2pdf#30]
Hi. For example, in document i have construction " [someText]{.someStyle} "

How to update .css file for print "someText" in red.

**Comment by jmaupetit** [comment]
You can create a new stylesheet (_e.g._ `styles.css`) with your own `.someStyle` rule:

```css
.someStyle {
  color: red;
}
```

... and add this CSS file to the command line options:

```
$ md2pdf --css styles.css foo.md foo.pdf
```

**Comment by nothanks1** [comment]
Not work on OSX. 

foo.md include: 
```
## Introduce

 This document prepared by [Red text here]{.critical} 
So sad. 
:(

## Tasks
```

And styles.css include: 
```
.critical {
  color: red;
}
```

After run command: md2pdf --css styles.css foo.md foo.pdf

![image](https://user-images.githubusercontent.com/15614493/71983706-69a1f300-3238-11ea-8d7a-b61575eb7293.png)


![image](https://user-images.githubusercontent.com/15614493/71983785-9bb35500-3238-11ea-8da4-b1cf76b1aac2.png)

I will try on debian.

**Comment by jmaupetit** [comment]
Ok, as this extra syntax is not implemented in the markdown library we are using, you will need to mix HTML in markdown:

```md
## Introduce

This document prepared by <span class="critical">Red text here</span>
```

**Comment by nothanks1** [comment]
Well, thank u!
