### ISSUE TITLE
Are Markdown Tables supported?

### ISSUE THREAD

**Issue by johnthagen** [jmaupetit/md2pdf#36]
Are Extended syntax tables supported? https://www.markdownguide.org/extended-syntax/#tables

### Code

```python
if __name__ == "__main__":
   table = """
| Syntax      | Description |
| ----------- | ----------- |
| Header      | Title       |
| Paragraph   | Text        |
"""

    output_path = Path("out.pdf")
    md2pdf(
        output_path,
        md_content=f"This is a **test**\n\n{table}",
        css_file_path=None,
        base_url=None
    )
```

### Output

Expecting to see a table here:

<img width="727" alt="Screen Shot 2021-01-20 at 12 56 29 PM" src="https://user-images.githubusercontent.com/10340167/105215174-f0153400-5b1e-11eb-987b-28628ae559c1.png">

### Version

Python 3.9.1

```
$ pip list
Package      Version
------------ -------
cairocffi    1.2.0
CairoSVG     2.5.1
cffi         1.14.4
cssselect2   0.4.1
defusedxml   0.6.0
docopt       0.6.2
html5lib     1.1
markdown2    2.3.10
md2pdf       0.4
Pillow       8.1.0
pip          20.3.3
prettytable  2.0.0
pycparser    2.20
Pyphen       0.10.0
setuptools   49.6.0
six          1.15.0
tinycss2     1.1.0
wcwidth      0.2.5
WeasyPrint   52.2
webencodings 0.5.1
wheel        0.35.1
```

**Comment by johnthagen** [comment]
Looking closer, it looks like the best thing to do would be to expose the `extras` attribute out to the user. `markdown2` supports this `extra`:

```
* tables: Tables using the same format as GFM
  <https://help.github.com/articles/github-flavored-markdown#tables> and
  PHP-Markdown Extra <https://michelf.ca/projects/php-markdown/extra/#table>.
```

Exposing this to the user would allow them to enable whichever extras they need.

**Comment by johnthagen** [comment]
I can confirm that setting `extras=["cuddled-lists", "tables"]` fixes this issue.

**Comment by johnthagen** [comment]
Related to #10

**Comment by jmaupetit** [comment]
Great! Can you propose a PR?

**Comment by jmaupetit** [comment]
This is now fixed! https://pypi.org/project/md2pdf/0.5/
