### ISSUE TITLE
Error module morkdown2

### ISSUE THREAD

**Issue by nCombo** [jmaupetit/md2pdf#5]
Linux:

Error when i try to excute "$ python setup.py install" : 
from markdown2 import markdown, markdown_path
ImportError: No module named markdown2

**Comment by jmaupetit** [comment]
Which version of python are you running? Did you try a `pip install -r requirements.txt` first?

**Comment by nCombo** [comment]
I use Ubuntu 14.04 LTS where Python 2.7 is default version. But i can switch to Python 3.4

**Comment by jmaupetit** [comment]
And have you tried to clone the project and run:

```bash
$ pip install -r requirements.txt
```

**Comment by nCombo** [comment]
To use md2pdf, I do : 
1. git clone https://github.com.jmaupetit/md2pdf.git
2. sudo apt-get libffi-dev (for ubuntu)
3. sudo pip install -r requirements.txt (for python)
4. sudo python setup.py install (to install md2pdf)
5. md2pdf --css my_markdown.css input.md output.pdf 

**notes:**
You may indicate step by step for new Python user 
Thank you for md2pdf

**Comment by jmaupetit** [comment]
Thank you for this contribution! I think it would be easier for non-pythonista to use the docker container. WDYT?
