### ISSUE TITLE
Question: Is there a CSS option to keep new lines in code snippets?

### ISSUE THREAD

**Issue by sarroutbi** [jmaupetit/md2pdf#74]
Hello. I am using `m2pdf` to create a PDF document from Markdown.

Original markdown document has a shell code snippet like:

```
$ operator-sdk run bundle --timeout 3m quay.io/sec-eng-special/tang-operator-bundle:v1.0.9
INFO[0008] Successfully created registry pod: quay-io-sec-eng-special-tang-operator-bundle-v1.0.9
...
INFO[0031] OLM has successfully installed "tang-operator.v1.0.9"
```                                                           

However, generated pdf does not keep newlines ... and the information is rendered like:
![image](https://github.com/jmaupetit/md2pdf/assets/959277/d986abb3-5591-4ae6-b32f-ad564fe82854)

Is there any CSS option for PDF output to keep new lines in code snippets?

Thanks !

**Comment by jmaupetit** [comment]
Which version do you run?
Is your code snippet wrapped using the triple backquotes syntax?

**Comment by sarroutbi** [comment]
> Which version do you run? 
I am running 1.0.1 version on Fedora 40

> Is your code snippet wrapped using the triple backquotes syntax?
Yes, it is. I have tried both, triple quotes with and without bash

**Comment by jmaupetit** [comment]
I haven't released it yet, but using the current `main` branch, activating the `fenced-code-blocks` extension should work:

```bash
md2pdf -e fenced-code-blocks input.md ouput.pdf
```

**Comment by sarroutbi** [comment]
> I haven't released it yet, but using the current `main` branch, activating the `fenced-code-blocks` extra should work:
> 
> ```shell
> md2pdf -e fenced-code-blocks input.md ouput.pdf
> ```
Nice. Thanks for your help.
