### ISSUE TITLE
Dependencies not automatically installed.

### ISSUE THREAD

**Issue by endrebak** [jmaupetit/md2pdf#8]
When I try `pip install md2pdf` the requirements are not automatically installed for some reason.

This might be because the requirements file is not directly accessible to `setup.py` on machines other than yours. I think a quickfix would just be to add the list of requirements to `setup.py`.

**Comment by endrebak** [comment]
Yeah, after installing the deps and then running `pip install` again I got: 

```
Collecting md2pdf
  Using cached md2pdf-0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_6lobc8r/md2pdf/setup.py", line 17, in <module>
        install_requires = open('requirements.txt').readlines(),
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
```

I think finding the requirements file before the package is installed is going to be mighty hard. Better to just add the list of requirements to `setup.py`.

**Comment by endrebak** [comment]
(I really like your tool btw. I search SO for ways to create text pdfs in python and yours is by far the easiest and most hacker-friendly.)

**Comment by jmaupetit** [comment]
Adding a `MANIFEST.in` file to this project is the key.
